backend:
  name: git-gateway

locale: "de"

media_folder: "web/site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Artikel" # Used in the UI, ie.: "New Post"
    folder: "web/site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Entwurf", name: "draft", widget: "boolean", default: true }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Bild", name: "image", widget: "image", required: false }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Seiten"
    files:
      - file: "web/site/content/_index.md"
        label: "Startseite"
        name: "home"
        fields:
          - { label: Titel, name: title, widget: string }
          - {
              label: Untertitel,
              name: subtitle,
              widget: string,
              required: false,
            }
          - { label: Bild, name: image, widget: image }
          - { label: 'Bild-Hintergrundfarbe', name: 'color', widget: 'color', required: true }
      - file: "web/site/content/rangliste/_index.md"
        label: "Rangliste"
        name: "rangliste"
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: "Datum", name: "date", widget: "datetime" }
          - { label: "Bild", name: "image", widget: "image", required: false }
          - { label: "Entwurf", name: "draft", widget: "boolean", default: true }
          - { label: "Text wenn nicht sichtbar", name: "notReadyText", widget: "text", required: true }
          - label: "Lied"
            name: "song"
            widget: "object"
            required: true
            fields: 
            - { label: "Titel", name: "title", widget: "string", required: true }
            - { label: "Beschreibung", name: "description", widget: "text", required: false }
            - { label: "Youtube-Link", name: "url", widget: "string", required: false }
            - { label: "Bild", name: image, widget: image, required: true }
