backend:
  name: git-gateway

locale: "de"

media_folder: "web/site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Artikel" # Used in the UI, ie.: "New Post"
    folder: "web/site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Entwurf", name: "draft", widget: "boolean", default: true }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Bild", name: "image", widget: "image", required: false }
      - { label: "Inhalt", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Seiten"
    files:
      - file: "web/site/content/_index.md"
        label: "Startseite"
        name: "home"
        fields:
          - { label: Titel, name: title, widget: string }
          - {
              label: Untertitel,
              name: subtitle,
              widget: string,
              required: false,
            }
          - { label: Bild, name: image, widget: image }
          - { label: 'Bild-Hintergrundfarbe', name: 'color', widget: 'color', required: true }
      - file: "web/site/content/rangliste/_index.md"
        label: "Rangliste"
        name: "rangliste"
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: "Datum", name: "date", widget: "datetime" }
          - { label: "Bild", name: "image", widget: "image", required: false }
          - { label: "Platzhalter-Text anzeigen", name: "showPlaceholder", widget: "boolean", default: true }
          - { label: "Platzhalter-Text", name: "placeholder", widget: "text", required: true }
          - label: "Lied"
            name: "song"
            widget: "object"
            required: true
            fields: 
            - { label: "Titel", name: "title", widget: "string", required: true }
            - { label: "Beschreibung", name: "description", widget: "text", required: false }
            - { label: "Youtube-Link", name: "url", widget: "string", required: false }
            - { label: "Bild", name: image, widget: image, required: true }
  - name: "game"
    label: "Tippspiel"
    files:
      - file: "web/game/countries.json"
        label: "Länder"
        name: "countries"
        fields:
          - label: "Länder"
            name: "countries"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Name", name: "name", widget: "string", required: true }
      - file: "web/game/players.json"
        label: "Spieler"
        name: "players"
        fields:
          - label: "Spieler"
            name: "players"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Name", name: "name", widget: "string", required: true }
      - file: "web/game/bets.json"
        label: "Tipps"
        name: "bets"
        fields:
          - label: "Tipps"
            name: "bets"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Land1", name: "country1", widget: "relation", collection: "game", file: "countries", search_fields: ["countries.*.name"], value_field: "countries.*.name", required: true }
              - { label: "Land2", name: "country2", widget: "relation", collection: "game", file: "countries", search_fields: ["countries.*.name"], value_field: "countries.*.name", required: true }
              - { label: "Land3", name: "country3", widget: "relation", collection: "game", file: "countries", search_fields: ["countries.*.name"], value_field: "countries.*.name", required: true }
              - { label: "Land4", name: "country4", widget: "relation", collection: "game", file: "countries", search_fields: ["countries.*.name"], value_field: "countries.*.name", required: true }
              - { label: "Europameister", name: "champion", widget: "relation", collection: "game", file: "countries", search_fields: ["countries.*.name"], value_field: "countries.*.name", required: true }
              - { label: "Torschützenkönig", name: "topScorer", widget: "relation", collection: "game", file: "players", search_fields: ["players.*.name"], value_field: "players.*.name", required: true }
      - file: "web/game/score.json"
        label: "Punkte"
        name: "score"
        fields:
          - label: "Punkte"
            name: "score"
            widget: "list"
            summary: "{{fields.country}} {{fields.victory}}"
            fields:
              - { label: "Land", name: "country", widget: "relation", collection: "game", file: "countries", search_fields: ["countries.*.name"], value_field: "countries.*.name", required: true }
              - { label: "Sieg", name: "victory", widget: "boolean", hint: "Wenn nicht, ist unentschieden" }
              - { label: "Beschreibung", name: "description", widget: "string", hint: "Text zur Erinnerung, damit nichts vergessen oder doppelt eingegeben wird." }
          - { label: "Europameister", name: "champion", widget: "relation", collection: "game", file: "countries", search_fields: ["countries.*.name"], value_field: "countries.*.name", required: false }
          - { label: "Torschützenkönig", name: "topScorer", widget: "relation", collection: "game", file: "players", search_fields: ["players.*.name"], value_field: "players.*.name", required: false }

